version: "3"
services:
    php-fpm:
      build: docker/php-fpm
      container_name: symfony-php-fpm
      working_dir: /var/www/html
      links:
        - mysql
      volumes:
        - ./catalog-rest:/var/www/html
        
    webserver:
      image: nginx:alpine
      container_name: symfony-webserver
      working_dir: /var/www/html
      volumes:
          - ./catalog-rest:/var/www/html
          - ./docker/nginx/default.template.conf:/etc/nginx/conf.d/default.template
      ports:
       - "8000:80"
      environment:
       - NGINX_HOST=${NGINX_HOST}
      command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
      restart: always
      links:
        - php-fpm
      depends_on:
            - php-fpm
            - mysql
    
    mysql:
      image: mysql
      container_name: symfony-mysql
      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}

