login:
    type: rest
    resource: AppBundle\Controller\RestLoginController
    
product:
    type: rest
    resource: AppBundle\Controller\ProductController
    
category:
    type: rest
    resource: AppBundle\Controller\CategoryController